title: "AbjadGenEval 2026"
#description: "Call for Participation: AbjadGenEval"
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: "https://forms.gle/NayQZxy1NDdmdbPz5"
  repository_name: "Registration Open"
markdown:
  kramdown:
    auto_ids: false  # This disables automatic heading IDs

